language: python
python:
  - 3.5
  - 3.6
install: 
  - pip install -r tests/requirements.txt
  - pip install --user codecov
  - python setup.py install
script:
  - py.test tests/score_test.py --cov=codecov
after_success:
  - codecov