language: python
python:
  - 3.5
  - 3.6
install: 
  - pip install -r tests/requirements.txt
  - python setup.py install
script:
  - coverage run --source sports setup.py test
after_success:
  coveralls